=== nirutasubedi01/Divine_Music_Store-/catalog_19031013.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="musicStore">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="storeDetails" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element ref="albums" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
</xs:element>
	<xs:element name="storeDetails">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="storeLogo"/>
				<xs:element ref="storeName"/>
				<xs:element ref="storeAddress"/>
				<xs:element ref="storeTelephoneNumber"/>
				<xs:element ref="storeWebSite"/>
			</xs:sequence>
			
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name ="storeAddress">
		<xs:complexType>
			<xs:choice>
				<xs:element name ="storeAddress1" type="xs:string"/>
				<xs:element name ="storeAddress2" type="xs:string"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

<xs:element name ="storeTelephoneNumber">
		<xs:complexType>
			<xs:choice>
				<xs:element name ="storePhoneNumber1" type="xs:string"/>
				<xs:element name ="storePhoneNumber2" type="xs:string"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>



	
	<xs:element name="storeName" type="xs:string"/>
	<xs:element name="storeWebSite" type="xs:string"/>
	<xs:element name="storeLogo"/>
	
	
	
	<xs:element name="albums">
		<xs:complexType>
			<xs:sequence>
			<xs:element ref="Kandara" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element ref="Resham" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element ref="Gantabya" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element ref="SaraSansar" minOccurs="1" maxOccurs="unbounded"/> 
			<xs:element ref="Karma" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="Kandara">
	<xs:complexType>
		<xs:sequence>
			
			<xs:element ref="kandara_image"  minOccurs="0" maxOccurs="unbounded"/>
			
			<xs:element ref="song"/>
			<xs:element ref="genre"/>
			<xs:element ref="music"/>
			<xs:element ref="Keyboards"/>
			<xs:element ref="Guitar"/>
			<xs:element ref="vocalist"/>
			<xs:element ref="artist"/>
			<xs:element ref="released_year"/>
			<xs:element ref="description"/>
			<xs:element ref="price"/>
			<xs:element ref="songDescription" minOccurs="1"/>
		</xs:sequence>
			<xs:attribute name="albumID" use="required" type="ID_Type"/>
	</xs:complexType>
</xs:element>	
	<xs:element name="Resham">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Resham_image" minOccurs="0" maxOccurs="unbounded" />
			
			<xs:element ref="song"/>
			<xs:element ref="genre"/>
			<xs:element ref="music"/>
			<xs:element ref="Keyboards"/>
			<xs:element ref="Guitar"/>
			<xs:element ref="vocalist"/>
			<xs:element ref="artist"/>
			<xs:element ref="released_year"/>
			<xs:element ref="description"/>
			<xs:element ref="price"/>
			<xs:element ref="songDescription" minOccurs="1"/>
		</xs:sequence>
		
			<xs:attribute name="reshamID" use="required" type="ID_Type" />
	</xs:complexType>
	</xs:element>
	
	<xs:element name="Gantabya">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Gantabya_image" minOccurs="0" maxOccurs="unbounded" />
			
			<xs:element ref="song"/>
			<xs:element ref="genre"/>
			<xs:element ref="music"/>
			<xs:element ref="Keyboards"/>
			<xs:element ref="Guitar"/>
			<xs:element ref="vocalist"/>
			<xs:element ref="artist"/>
			<xs:element ref="released_year"/>
			<xs:element ref="description"/>
			<xs:element ref="price"/>
			<xs:element ref="songDescription" minOccurs="1"/>
		</xs:sequence>
		
			<xs:attribute name="gantabyaID" use="required" type="ID_Type"/>
	</xs:complexType>
	</xs:element>


	<xs:element name="SaraSansar">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="SaraSansar_image" minOccurs="0" maxOccurs="unbounded" />
			
			<xs:element ref="song"/>
			<xs:element ref="genre"/>
			<xs:element ref="music"/>
			<xs:element ref="Keyboards"/>
			<xs:element ref="Guitar"/>
			<xs:element ref="vocalist"/>
			<xs:element ref="artist"/>
			<xs:element ref="released_year"/>
			<xs:element ref="description"/>
			<xs:element ref="price"/>
			<xs:element ref="songDescription" minOccurs="1"/>
		</xs:sequence>
		
			<xs:attribute name="sarasansarID" use="required" type="ID_Type"/>
	</xs:complexType>
	</xs:element>
	
		<xs:element name="Karma">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="Karma_image" minOccurs="0" maxOccurs="unbounded"/>
			
			<xs:element ref="song"/>
			<xs:element ref="genre"/>
			<xs:element ref="music"/>
			<xs:element ref="Keyboards"/>
			<xs:element ref="Guitar"/>
			<xs:element ref="vocalist"/>
			<xs:element ref="artist"/>
			<xs:element ref="released_year"/>
			<xs:element ref="description"/>
			<xs:element ref="price"/>
			<xs:element ref="songDescription" minOccurs="1"/>
		</xs:sequence>
	
			<xs:attribute name="karmaID" use="required" type="ID_Type"/>
	</xs:complexType>
	</xs:element>
<xs:element name="kandara_image"/>


<xs:element name="Resham_image"/>


<xs:element name="Gantabya_image"/>


<xs:element name="SaraSansar_image"/>


<xs:element name="Karma_image"/>


<xs:element name="song" type="xs:string"/>
<xs:element name="genre" type="xs:string"/>
<xs:element name="music" type="xs:string"/>
<xs:element name="Keyboards" type="xs:string"/>
<xs:element name="Guitar" type="xs:string"/>
<xs:element name="vocalist" type="xs:string"/>
<xs:element name="artist" type="xs:string"/>
<xs:element name="released_year" type="xs:string"/>
<xs:element name="description" type="xs:string"/>
<xs:element name="price" type="xs:string"/>



<xs:element name="songDescription">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="duration"/>
			<xs:element ref="video"/>
			<xs:element ref="playback_speed"/>
	
</xs:sequence>
			<xs:attribute name = "song_title" use= "required"/>
			<xs:attribute name = "songID" use= "required" type="ID_Type"/>
</xs:complexType>
</xs:element>	
	
<xs:element name="duration" type="xs:string"/>
<xs:element name="video" type="choose"/>
<xs:element name = "playback_speed" type="xs:string"/>

<xs:simpleType name="choose">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Quality: Full Hd" />
			<xs:enumeration value="Quality: Hd " />
			
		</xs:restriction>
</xs:simpleType>

<xs:simpleType name="ID_Type" >
	<xs:restriction base="xs:string">
		<xs:pattern value="[A-Z0-9]{6}"/>
	</xs:restriction>
</xs:simpleType>

</xs:schema>

=== nirutasubedi01/Divine_Music_Store-/catalog_19031013.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/css" href="catalog_19031013.css"?> 

<musicStore 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="catalog_19031013.xsd">
<storeDetails>
<storeLogo>
		<html xmlns="http://www.w3.org/1999/xhtml">
			<img src="logo.jpg"/>
		</html>	
	</storeLogo>
	<storeName>Divine Music Store</storeName>
	<storeAddress>
	<storeAddress1>Address:Devi's Fall , Pokhara-17, Nepal</storeAddress1>
	
	</storeAddress>
	<storeTelephoneNumber>
		<storePhoneNumber1>Contact Number: 9846219429</storePhoneNumber1>
		
	</storeTelephoneNumber>
	<storeWebSite>Web Site:www.seedivine011.com.np</storeWebSite>
</storeDetails>

<albums>	
	<Kandara  albumID="C21645">
	<kandara_image>
	<html xmlns="http://www.w3.org/1999/xhtml">
			<img id="kk1" src="kandara3.jpg" width="400" height="400"/>
		</html>
	</kandara_image>
		<song> Timi Pari </song>
		<genre> Jaaz </genre>
		<music> Suni Thapa </music>
		<Keyboards> Buddha Raj Bajracharya  </Keyboards>
		<Guitar> Amit Gurung </Guitar>
		<vocalist> Bibek Shrestha </vocalist>
		<artist> Kandara </artist>
		<released_year>1996</released_year>
		<description>  
		This is one of the beautiful song among 8 songs of the album Danda Pari which is 
		released in 1996. The mutal collabration among the team seems to the best and have huge 
		public support and love. </description>
		<price> 120</price>
		<songDescription songID="T65150" song_title=" 1996 TimiPari">
			<duration>  6:04 minutes </duration>
			<video>Quality: Full Hd</video>
			<playback_speed> Normal</playback_speed>
		</songDescription>
	</Kandara>
	
	<Kandara albumID="C22645">
	<kandara_image>
	<html xmlns="http://www.w3.org/1999/xhtml">
			<img src="kandara2.jpg" width="400" height="400"/>
		</html>
	</kandara_image>
		<song> Lekha ke hye Maya" </song>
		<genre>Jaaz</genre>
		<music> Suni Thapa </music>
		<Keyboards> Buddha Raj Bajracharya  </Keyboards>
		<Guitar> Amit Gurung </Guitar>
		<vocalist> Bibek Shrestha </vocalist>
		<artist> Kandara </artist>
		<released_year> 1997</released_year>
		<description>  
		This is one of the beautiful song among 8 songs of the album Danda Pari which is 
		released in 1997. The mutal collabration among the team seems to the best and have huge 
		public support and love. </description>
		<price> 120</price>
		<songDescription songID="L65050" song_title="Lekha ke 1997">
			<duration>6:04 minutes </duration>
			<video>Quality: Full Hd</video>
			<playback_speed> Normal</playback_speed>
		</songDescription>
	</Kandara>
	
	
	<Kandara albumID="C23645">
	<kandara_image>
	<html xmlns="http://www.w3.org/1999/xhtml">
			<img src="kandara.jpg" width="400" height="400"/>
		</html>
	</kandara_image>
		<song> Dada Pari</song>
		<genre>Jaaz</genre>
		<music> Suni Thapa </music>
		<Keyboards> Buddha Raj Bajracharya  </Keyboards>
		<Guitar> Amit Gurung </Guitar>
		<vocalist> Bibek Shrestha </vocalist>
		<artist> Kandara </artist>
			<released_year> 1997</released_year>
		<description>  
		This is one of the beautiful song among 8 songs of the album Danda Pari which is 
		released in 1997. The mutal collabration among the team seems to the best and have huge 
		public support and love. </description>
		<price> 120 </price>
		<songDescription songID="L60506" song_title="Danda 1997">
			<duration> 6:04 minutes </duration>
			<video>Quality: Full Hd</video>
			<playback_speed> Normal</playback_speed>
		</songDescription>
	</Kandara>
	
	

	
	<Resham reshamID="C24645">
		<Resham_image>
	<html xmlns="http://www.w3.org/1999/xhtml">
			<img src="Resham.jpg" width="400" height="400"/>
		</html>
	</Resham_image>
		<song> Aaina Jhyal</song>
		<genre> Country music</genre>
		<music> Madhav Prasad Ghimire </music>
		<Keyboards>   </Keyboards>
		<Guitar> Amit Gurung </Guitar>
		<vocalist> Amrit Gurung  </vocalist>
		<artist> Nepathya </artist>
			<released_year> 1999</released_year>
		<description>  
		The album Resham contains total ten albums, One of the melodious song is Aaina Jhyal which is released
		in year 2012. And band have collect huge public support and love. </description>
		<price> 100 </price>
		<songDescription songID="R60505" song_title="Aaina 1999">
			<duration> 4:22 minutes </duration>
			<video>Quality: Full Hd</video>
			<playback_speed> Normal</playback_speed>
		</songDescription>
	</Resham>
	
	<Resham reshamID="C25645">
		<Resham_image>
	<html xmlns="http://www.w3.org/1999/xhtml">
			<img src="Resham2.jpg" width="400" height="400"/>
		</html>
	</Resham_image>
		<song> Ukali Oorali</song>
		<genre> Country Music </genre>
		<music> Madhav Prasad Ghimire </music>
		<Keyboards>   </Keyboards>
		<Guitar> Amit Gurung </Guitar>
		<vocalist> Amrit Gurung  </vocalist>
		<artist> Nepathya </artist>
			<released_year> 2000</released_year>
		<description>  
		 The album Resham contains total ten albums, One of the melodious song is 
		 Ukali Oorali which is releasedin year 2008. And band have collect huge
		 public support and love. </description>
		<price> 120 </price>
		<songDescription songID="R60506" song_title="Ukali 2000">
			<duration> 6:04 minutes </duration>
			<video>Quality: Full Hd</video>
			<playback_speed> Normal</playback_speed>
		</songDescription>
	</Resham>
	
	
	
	<Resham reshamID="C26645">
		<Resham_image>
	<html xmlns="http://www.w3.org/1999/xhtml">
			<img src="Resham3.jpg" width="400" height="400"/>
		</html>
	</Resham_image>
		<song> Yani Maya</song>
		<genre> Country  Music</genre>
		<music> Madhav Prasad Ghimire </music>
		<Keyboards>Shyam Das   </Keyboards>
		<Guitar> Amit Gurung </Guitar>
		<vocalist> Amrit Gurung  </vocalist>
		<artist> Nepathya </artist>
			<released_year> 2013</released_year>
		<description>  
		 The album Resham contains total ten albums, One of the melodious song is 
		 Yani Maya which is releasedin year 2008. And band have collect huge
		 public support and love.</description>
		<price> 120 </price>
		<songDescription songID="R60507" song_title="Yanimaya 2013">
			<duration> 6:04 minutes </duration>
			<video>Quality: Full Hd</video>
			<playback_speed> Normal</playback_speed>
		</songDescription>
	</Resham>
	
	
	
	<Gantabya gantabyaID="C27645">
		<Gantabya_image>
	<html xmlns="http://www.w3.org/1999/xhtml">
			<img src="Gantabya.jpg" width="400" height="400"/>
		</html>
	</Gantabya_image>
		<song> Timro Yaad</song>
		<genre> Pop Song </genre>
		<music> Samrat Magar</music>
		<Keyboards> Surya Gurung  </Keyboards>
		<Guitar> Bishnu Gurung </Guitar>
		<vocalist> Jeewan  Gurung  </vocalist>
		<artist> The Edge Band </artist>
			<released_year> 2000</released_year>
		<description>  
		One of the most beautiful song which is was released in year 2016
		with the music video. The album contain total 7 songs. Timro Yaad is 
		the first song of the fifth studio album “Gantabya” performed by 
		The Edge Band. The song Timro Yaad Lyrics is written by The Edge Band 
		as well as composed and arranged by The Edge Band.The music video of
		Timro Yaad is beautifully directed by Suraya Gurung.While the starring
		role is done by Samrat Magar and  Neelum Chand.</description>
		<price> 110</price>
		<songDescription songID="T60501" song_title="Timro 2000">
			<duration> 6:04 minutes </duration>
			<video>Quality: Full Hd</video>
			<playback_speed> Normal</playback_speed>
		</songDescription>
	</Gantabya>
	
	
	<Gantabya gantabyaID="C28645">
		<Gantabya_image>
	<html xmlns="http://www.w3.org/1999/xhtml">
			<img src="Gantabya2.jpg" width="400" height="400"/>
		</html>
	</Gantabya_image>
		<song> Kasto Yo din </song>
		<genre> Pop Song </genre>
		<music> Samrat Magar</music>
		<Keyboards> Surya Gurung  </Keyboards>
		<Guitar> Bishnu Gurung </Guitar>
		<vocalist> Jeewan  Gurung  </vocalist>
		<artist> The Edge Band </artist>
			<released_year> 1998</released_year>
		<description>  
		Kasto Yo Din is the second song of the fifth studio album “Gantabya” performed by
		The Edge Band. The song Kasto Yo Din Lyrics is written by The Edge Band, 
		as well as composed and arranged by The Edge Band.This song is pubished on 
		20,October 2016. </description>
		<price> 110</price>
		<songDescription songID="T60502" song_title="Kasto 1998">
			<duration> 6:00 minutes </duration>
			<video>Quality: Full Hd</video>
			<playback_speed> Normal</playback_speed>
		</songDescription>
	</Gantabya>
	
	<Gantabya gantabyaID="C20645">
		<Gantabya_image>
	<html xmlns="http://www.w3.org/1999/xhtml">
			<img src="Gantabya3.jpg" width="400" height="400"/>
		</html>
	</Gantabya_image>
		<song> Samjhera</song>
		<genre> Pop Song </genre>
		<music> Rohit Shakya</music>
		<Keyboards> Surya Gurung  </Keyboards>
		<Guitar> Bishnu Gurung </Guitar>
		<vocalist> Jeewan  Gurung  </vocalist>
		<artist> The Edge Band </artist>
			<released_year> 2009</released_year>
		<description>  
		Samjhera is the second song of the fifth studio album “Gantabya” performed by
		The Edge Band. The song Samjhera is written by The Edge Band, as well as 
		composed and arranged by The Edge Band.This song is pubished on 20,October 2016. </description>
		<price> 110</price>
		<songDescription songID="T60503" song_title="Samjhera 2009">
			<duration> 5:04 minutes </duration>
			<video>Quality: Full Hd</video>
			<playback_speed> Normal</playback_speed>
		</songDescription>
	</Gantabya>
	
	
	

	
	<SaraSansar sarasansarID="C20045">
		<SaraSansar_image>
	<html xmlns="http://www.w3.org/1999/xhtml">
			<img src="SaraSansar.jpg" width="400" height="400"/>
		</html>
	</SaraSansar_image>
		<song> Sadhai Sadhai </song>
		<genre> Rock Song </genre>
		<music> Rohit Shakya</music>
		<Keyboards>Manish Thapa</Keyboards>
		<Guitar>Pragya </Guitar>
